import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { QueryProvider } from '@/components/provider/query-provider';
import { BackgroundPattern } from '@/components/background-pattern';
import { TracingBeam } from '@/components/tracing-beam';

const inter = Poppins({ subsets: ['latin'], weight: ['400', '600', '900'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn(inter.className, 'overscroll-none')}>
        <BackgroundPattern />
        <QueryProvider>
          <main className='h-full max-h-full'>
            <TracingBeam>{children}</TracingBeam>
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
